### ISSUE TITLE
download_images.py /Data/Roads/_Links/Images.txt

### ISSUE THREAD

**Issue by kartalsez** [Paulymorphous/Road-Segmentation#1]
Hello Pauly,

I liked your source code and your approach. But I saw that there aren't some files.
When I run download_images.py script, I take this error: **FileNotFoundError: [Errno 2] No such file or directory: '../Data/Roads/_Links/Images.txt'**
- I can't see Images.txt in project files. ( /Data/Roads/_Links/Images.txt)
- I can't see road_images.h5py (./Data/road_images.h5py) and  road_masks.h5py (./Data/road_masks.h5py) files.

Can you

**Comment by Paulymorphous** [comment]
Hey, 
I have added the link files. You can download the images using the script now.
road_images.h5py are quite heavy, that's why I didn't upload them. However, you can use the scripts to create these files after downloading the images. 
All the Best.

**Comment by ujwalakoriraj** [comment]
Could you please 

> Hey,
> I have added the link files. You can download the images using the script now.
> road_images.h5py are quite heavy, that's why I didn't upload them. However, you can use the scripts to create these files after downloading the images.
> All the Best.

Could you please share the code for creating .hfpy files for 'images' and 'labels'? I have not been able to load the .tiff images.

This is my code:
`import h5py
import os
import PIL
from glob import glob


images_path="D:/python/building_detection/8_building/data/building/images"

images = glob(os.path.join(images_path, "*.tiff"))


IMAGE_HEIGHT = IMAGE_WIDTH = 256
NUM_CHANNELS = 3

with h5py.File('building_images.h5', 'w') as hf:
    for i,img in enumerate(images): 
        image=PIL.Image.open(img)
        Xset = hf.create_dataset(
                name='X'+str(i),
                data=image,
                shape=(IMAGE_HEIGHT, IMAGE_WIDTH, NUM_CHANNELS),
                maxshape=(IMAGE_HEIGHT, IMAGE_WIDTH, NUM_CHANNELS))`

And this is what it says:
*********
  File "C:\Users\rajak\anaconda3\envs\road\lib\site-packages\h5py\_hl\dataset.py", line 77, in make_new_dset
    raise ValueError("Shape tuple is incompatible with data")

ValueError: Shape tuple is incompatible with data
***********

**Comment by f3rhoodn** [comment]
> 
> 
> > Hey,
> > I have added the link files. You can download the images using the script now.
> > road_images.h5py are quite heavy, that's why I didn't upload them. However, you can use the scripts to create these files after downloading the images.
> > All the Best.
> 
> Could you please share the code for creating .hfpy files for 'images' and 'labels'? I have not been able to load the .tiff images.
> 
> This is my code:
> `import h5py
> import os
> import PIL
> from glob import glob
> 
> images_path="D:/python/building_detection/8_building/data/building/images"
> 
> images = glob(os.path.join(images_path, "*.tiff"))
> 
> IMAGE_HEIGHT = IMAGE_WIDTH = 256
> NUM_CHANNELS = 3
> 
> with h5py.File('building_images.h5', 'w') as hf:
> for i,img in enumerate(images):
> image=PIL.Image.open(img)
> Xset = hf.create_dataset(
> name='X'+str(i),
> data=image,
> shape=(IMAGE_HEIGHT, IMAGE_WIDTH, NUM_CHANNELS),
> maxshape=(IMAGE_HEIGHT, IMAGE_WIDTH, NUM_CHANNELS))`
> 
> And this is what it says:
> 
> File "C:\Users\rajak\anaconda3\envs\road\lib\site-packages\h5py_hl\dataset.py", line 77, in make_new_dset
> raise ValueError("Shape tuple is incompatible with data")
> 
> ValueError: Shape tuple is incompatible with data

were you able to solve this problem?
