### ISSUE TITLE
StopIteration   error

### ISSUE THREAD

**Issue by sathwiksathi** [Paulymorphous/Road-Segmentation#6]
![Annotation 2020-04-03 133920](https://user-images.githubusercontent.com/49642842/78338549-a029a880-75b0-11ea-87f4-6873714367ba.png)

**Comment by Paulymorphous** [comment]
Please check the path to the directory. Changing the root_path to point to the project root directory in your system will fix this error. 

os.walk raises a StopIteration error when the iterator is unable to find any directory to Iterate.
